### ISSUE TITLE
Publish plugin to wordpress.org

### ISSUE THREAD

**Issue by claytoncollie** [darrenjacoby/intervention#102]
Have you given any thought to publishing this plugin to wordpress.org? It's actually really easy nowadays with [this GitHub Action](https://github.com/claytoncollie/tracking-code-for-google-analytics/blob/master/.github/workflows/deploy.yml). I have my plugins automatically published to the repo without leaving GitHub. You would not need [this part](https://github.com/soberwp/intervention/blob/974043c1d1629e0cdc384f408fd1269a6f74b702/intervention.php#L12-L13) of your current codebase if you went this route and the end-user would not need to have Andy's plugin updater plugin also activated. Happy to make a PR if you are interested.

**Comment by darrenjacoby** [comment]
Hey @claytoncollie,

Yes, I have been planning on moving to wordpress.org. I first had to implement [php-scoper](https://github.com/humbug/php-scoper) to namespace vendor namespaces to avoid conflicts, but that's part of the new release. I will likely publish that branch later today, or in the coming days.

I would love a PR for the GH action though!

**Comment by darrenjacoby** [comment]
@claytoncollie if you do have time to submit a PR, would you mind working from branch `interface`? That's the latest. 

Also feel free to take it for a test-run. It requires more testing, but has an interface for the admin section under Tools→Intervention.
