### ISSUE TITLE
Add support for WordPress code style/format/linting

### ISSUE THREAD

**Issue by claytoncollie** [darrenjacoby/intervention#107]
I opened the plugin files up in my VS Code and noticed a ton of formatting issues. I have my machine set to use the [WordPress-Extra standard](https://github.com/WordPress/WordPress-Coding-Standards) when writing code. Would you be open to linting this entire plugin against a standard? We can have it run against all pull requests and all releases/deployments as well. I would be happy to work on this although it would be a huge PR (could be in pieces) since it will probably touch every single file. This is a [nice article](https://javorszky.co.uk/2018/07/30/set-up-phpcs-and-wordpress-extra-coding-standards-and-configure-your-ides-to-use-them/) to get you going with PHPCS. Sorry if you already know about/how to do this 😄

**Comment by claytoncollie** [comment]
Sorry, just now seeing this is the standard `symplify/easy-coding-standard`

**Comment by darrenjacoby** [comment]
@claytoncollie I'm open to review it actually, `symplify/easy-coding-standard` was a contribution. I am not a fan of the WordPress coding standards, but open to implementing PSR-12.

**Comment by darrenjacoby** [comment]
Closing for now.
