### ISSUE TITLE
[Featured Request] Additional Page Attribute Settings

### ISSUE THREAD

**Issue by bigskillet** [darrenjacoby/intervention#115]
Allow the selection of a page template, but restrict the ability to choose a parent:

```
'pages.item.attributes.parent',
'pages.item.attributes.template',
'pages.item.attributes.order'
```

**Comment by darrenjacoby** [comment]
@bigskillet for the block editor?

**Comment by bigskillet** [comment]
I was referring to the classic editor actually, but I assume the page attributes metabox would be the same for the block editor, or no?

**Comment by darrenjacoby** [comment]
@bigskillet will look into this!
